import "~/styles/globals.css";
import { MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import HeaderBar from "./admin/events/HeaderBar";

export const metadata: Metadata = {
  title: "FtC",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <MantineProvider>
          <Notifications />
          <TRPCReactProvider>
            <HeaderBar />
            {children}
          </TRPCReactProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
